name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
    contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      # Build for different platforms - targeting just the main project
      - name: Publish Windows
        run: dotnet publish vehicles-management-system.csproj -c Release -r win-x64 --self-contained -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/win-x64
      
      - name: Publish Linux
        run: dotnet publish vehicles-management-system.csproj -c Release -r linux-x64 --self-contained -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/linux-x64
      
      - name: Publish macOS (Intel)
        run: dotnet publish vehicles-management-system.csproj -c Release -r osx-x64 --self-contained -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/osx-x64
      
      - name: Publish macOS (ARM)
        run: dotnet publish vehicles-management-system.csproj -c Release -r osx-arm64 --self-contained -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/osx-arm64

      # Create data directory and include sample data
      - name: Prepare data directory
        run: |
          mkdir -p ./publish/win-x64/data
          mkdir -p ./publish/linux-x64/data
          mkdir -p ./publish/osx-x64/data
          mkdir -p ./publish/osx-arm64/data
          cp -r ./data/* ./publish/win-x64/data/
          cp -r ./data/* ./publish/linux-x64/data/
          cp -r ./data/* ./publish/osx-x64/data/
          cp -r ./data/* ./publish/osx-arm64/data/

      # Create zip archives
      - name: Zip Windows build
        run: cd ./publish/win-x64 && zip -r ../../VehicleManagementSystem-windows.zip .
      
      - name: Zip Linux build
        run: cd ./publish/linux-x64 && zip -r ../../VehicleManagementSystem-linux.zip .
      
      - name: Zip macOS (Intel) build
        run: cd ./publish/osx-x64 && zip -r ../../VehicleManagementSystem-macos-intel.zip .
        
      - name: Zip macOS (ARM) build
        run: cd ./publish/osx-arm64 && zip -r ../../VehicleManagementSystem-macos-arm.zip .

      # Extract version from tag
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      # Create GitHub Release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Vehicle Management System v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            VehicleManagementSystem-windows.zip
            VehicleManagementSystem-linux.zip
            VehicleManagementSystem-macos-intel.zip
            VehicleManagementSystem-macos-arm.zip
          body: |
            # Vehicle Management System v${{ steps.get_version.outputs.VERSION }}
            
            ## Release Notes
            
            ### Vehicle Management
            - Multiple vehicle types (Car, Truck, Boat, Airplane, Train)
            - Specialized vehicle types (RaceCar, LuxuryYacht, CargoAirplane)
            - Custom attributes for each vehicle type
            - Vehicle creation, reading, updating, and deletion operations
            
            ### Financial Features
            - Tax calculation based on vehicle type and value
            - Price comparisons between vehicles
            - Value-based sorting and filtering
            
            ### Data Operations
            - Save/load vehicle data from CSV files
            - Custom file location support
            - Error handling and data validation
            
            ### Analysis Tools
            - Vehicle statistics generation
            - Cross-vehicle type comparisons
            - Performance metrics for different vehicle categories
            
            ### System Requirements
            - .NET 9.0+ runtime
            - 100MB disk space
            - 4GB RAM recommended
            
            ### Resolved Issues
            - Resolved macOS build issues

            ### Known Issues
            - None at this time
